#!/usr/bin/env perl
# Copyright 2009-2012 Kevin Spencer <kevin@kevinspencer.org>
#
# Permission to use, copy, modify, distribute, and sell this software and its
# documentation for any purpose is hereby granted without fee, provided that
# the above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation.  No representations are made about the suitability of this
# software for any purpose.  It is provided "as is" without express or 
# implied warranty.
#
################################################################################

use HTML::Entities;
use strict;
use warnings;

our $VERSION = '0.03';

my $bit_rate_limit = shift;
$bit_rate_limit ||= 192;

my $user = getpwuid($<);
my $library_path = "/Users/$user/Music/iTunes/iTunes Music Library.xml";
open(my $lfh, '<', $library_path) || die "Could not open $library_path - $!\n";
my ($artist, $album, %list);
while (<$lfh>) {
    my $line = $_;
    if ($line =~ /<key>Artist<\/key><string>(.+)<\/string>/) {
        $artist = decode_entities($1);
    } elsif ($line =~ /<key>Album<\/key><string>(.+)<\/string>/) {
        $album = $1;
    } elsif ($line =~ /<key>Bit Rate<\/key><integer>(\d+)<\/integer>/) {
        my $bit_rate = $1;
        if ($bit_rate < $bit_rate_limit) {
            my $key = "$artist - $album";
            $list{$key} = $bit_rate;
        }
    }
}
close($lfh);
if (%list) {
    for my $key (sort(keys(%list))) {
        print "$key: $list{$key}\n";
    }
}

